// <auto-generated />
using System;
using Lifestyle_Preference_survey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lifestyle_Preference_survey.Migrations
{
    [DbContext(typeof(AppBDContext))]
    [Migration("20250530104734__Init")]
    partial class _Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.Foods", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Other")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PapAndWors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pasta")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pizza")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserDetailID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("UserDetailID");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.Rating", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Movies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Out")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Radio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TV")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserDetailID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("UserDetailID");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.UserDetails", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullnames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.Foods", b =>
                {
                    b.HasOne("Lifestyle_Preference_survey.Models.UserDetails", "UserDetail")
                        .WithMany()
                        .HasForeignKey("UserDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDetail");
                });

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.Rating", b =>
                {
                    b.HasOne("Lifestyle_Preference_survey.Models.UserDetails", "UserDetail")
                        .WithMany()
                        .HasForeignKey("UserDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
