// <auto-generated />
using System;
using Lifestyle_Preference_survey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lifestyle_Preference_survey.Migrations
{
    [DbContext(typeof(AppBDContext))]
    partial class AppBDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.Foods", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PapAndWors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pasta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pizza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.Rating", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Movies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Out")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Lifestyle_Preference_survey.Models.UserDetails", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullnames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
